const db = require('../../utils/db');
const neon = require('../../utils/neon');
const LogService = require('../../services/logService');
const CacheService = require('../../services/cacheService');
const logger = require('../../utils/logger');

/**
 * Settings Controller
 * Handles system-wide configuration and metadata using Neon PostgreSQL.
 */
const getSettings = async (req, res) => {
  try {
    const cacheKey = 'system_settings';
    let settings = await CacheService.get(cacheKey);

    if (!settings) {
      const { data, error } = await db
        .from('Setting')
        .select('*')
        .eq('id', 1)
        .maybeSingle();

      if (error) throw error;
      settings = data;

      if (!settings) {
        // Initialize default settings if row 1 doesn't exist
        const now = new Date().toISOString();
        const defaultPaymentMethods = [
          { 
            name: 'bKash', 
            number: '01322511554', 
            instructions: 'Send money to this bKash personal number (01322511554) and enter the TrxID below.', 
            isActive: true, 
            themeColor: '#E2136E', 
            logoUrl: '' 
          },
          { 
            name: 'Nagad', 
            number: '01700000000', 
            instructions: 'Send money to this Nagad personal number and enter the TrxID below.', 
            isActive: true, 
            themeColor: '#F7931E', 
            logoUrl: '' 
          }
        ];

        const { data: created, error: insertError } = await db
          .from('Setting')
          .insert([{
            id: 1,
            registrationFee: 365,
            employeeCanViewAll: false,
            jobApplicationsEnabled: true,
            paymentMethods: defaultPaymentMethods,
            smsWebhookKey: require('crypto').randomBytes(24).toString('hex'),
            createdAt: now,
            updatedAt: now
          }])
          .select()
          .single();

        if (insertError) throw insertError;
        settings = created;
      }

      await CacheService.set(cacheKey, settings, 3600);
    }

    // Set HTTP cache header for edge performance
    res.setHeader('Cache-Control', 'private, no-cache, no-store, must-revalidate');
    res.json({ ...settings, _id: settings.id, id: settings.id });
  } catch (error) {
    logger.error('Failed to get settings:', error);
    res.status(500).json({ message: error.message });
  }
};

const updateSettings = async (req, res) => {
  try {
    if (req.user.role !== 'owner') return res.status(403).json({ message: 'Owner only' });

    const updates = {};
    if (req.body.registrationFee !== undefined) updates.registrationFee = parseInt(req.body.registrationFee);
    if (req.body.paymentMethods !== undefined) updates.paymentMethods = req.body.paymentMethods;
    if (req.body.employeeCanViewAll !== undefined) updates.employeeCanViewAll = Boolean(req.body.employeeCanViewAll);
    if (req.body.jobApplicationsEnabled !== undefined) updates.jobApplicationsEnabled = Boolean(req.body.jobApplicationsEnabled);
    if (req.body.smsWebhookKey !== undefined) updates.smsWebhookKey = req.body.smsWebhookKey;
    updates.updatedAt = new Date().toISOString();

    const { data: updated, error } = await db
      .from('Setting')
      .update(updates)
      .eq('id', 1)
      .select()
      .single();

    if (error) throw error;

    await CacheService.invalidateSettings();

    await LogService.info(
      `System settings updated by admin`,
      'ADMIN_UPDATE_SETTINGS',
      null,
      { adminId: req.user.id }
    ).catch(() => {});

    res.json({ ...updated, _id: updated.id, id: updated.id });
  } catch (error) {
    logger.error('Failed to update settings:', error);
    res.status(500).json({ message: error.message });
  }
};

const regenerateSmsApiKey = async (req, res) => {
  try {
    if (req.user.role !== 'owner') return res.status(403).json({ message: 'Owner only' });

    const newKey = require('crypto').randomBytes(24).toString('hex');

    const { data: updated, error } = await db
      .from('Setting')
      .update({ smsWebhookKey: newKey, updatedAt: new Date().toISOString() })
      .eq('id', 1)
      .select()
      .single();

    if (error) throw error;

    await CacheService.invalidateSettings();

    LogService.info(
      `SMS Webhook API Key regenerated by admin`,
      'ADMIN_REGENERATE_SMS_KEY',
      null,
      { adminId: req.user.id }
    ).catch(err => logger.error('Audit logging failed:', err));

    res.json({ key: newKey });
  } catch (error) {
    logger.error('SMS Key Regeneration Failed:', error);
    res.status(500).json({ 
      message: error.message || 'Internal server error'
    });
  }
};

module.exports = { getSettings, updateSettings, regenerateSmsApiKey };
