const crypto = require('crypto');
const supabase = require('../../utils/supabase');
const LogService = require('../../services/logService');
const CacheService = require('../../services/cacheService');
const logger = require('../../utils/logger');

/**
 * Settings Controller
 * Handles system-wide configuration and metadata.
 */
const Settings = require('../../models/Settings');

/**
 * Settings Controller
 * Handles system-wide configuration and metadata using MongoDB.
 */
const getSettings = async (req, res) => {
  try {
    const cacheKey = 'system_settings';
    let settings = await CacheService.get(cacheKey);

    if (!settings) {
      // 1. Try to find in MongoDB
      settings = await Settings.findOne();

      // 2. Fallback/Migration: If not in Mongo, check Supabase
      if (!settings) {
        const { data: sbSettings } = await supabase.from('Setting').select('*').eq('id', 1).maybeSingle();
        
        if (sbSettings) {
          // Migrate Supabase data to MongoDB
          settings = await Settings.create({
            registrationFee: sbSettings.registrationFee,
            jobApplicationsEnabled: sbSettings.jobApplicationsEnabled,
            employeeCanViewAll: sbSettings.employeeCanViewAll,
            paymentMethods: sbSettings.paymentMethods,
            smsWebhookKey: sbSettings.smsWebhookKey || Array.from({length: 48}, () => Math.floor(Math.random() * 16).toString(16)).join('')
          });
          logger.info('Migrated settings from Supabase to MongoDB');
        } else {
          // Initialize fresh in MongoDB
          settings = await Settings.create({
            registrationFee: 365,
            employeeCanViewAll: false,
            jobApplicationsEnabled: true
          });
          logger.info('Initialized default settings in MongoDB');
        }
      }
      
      await CacheService.set(cacheKey, settings, 3600);
    }

    res.json({ ...settings.toObject(), _id: settings._id, id: 1 });
  } catch (error) {
    logger.error('Failed to get settings:', error);
    res.status(500).json({ message: error.message });
  }
};

const updateSettings = async (req, res) => {
  try {
    if (req.user.role !== 'owner') return res.status(403).json({ message: 'Owner only' });

    let settings = await Settings.findOne();
    if (!settings) settings = new Settings();

    if (req.body.registrationFee !== undefined) settings.registrationFee = parseInt(req.body.registrationFee);
    if (req.body.paymentMethods) settings.paymentMethods = req.body.paymentMethods;
    if (req.body.employeeCanViewAll !== undefined) settings.employeeCanViewAll = Boolean(req.body.employeeCanViewAll);
    if (req.body.jobApplicationsEnabled !== undefined) settings.jobApplicationsEnabled = Boolean(req.body.jobApplicationsEnabled);
    if (req.body.smsWebhookKey !== undefined) settings.smsWebhookKey = req.body.smsWebhookKey;
    
    await settings.save();
    await CacheService.invalidateSettings();

    await LogService.info(
      `System settings updated by admin`,
      'ADMIN_UPDATE_SETTINGS',
      null,
      { adminId: req.user.id }
    );

    res.json({ ...settings.toObject(), _id: settings._id, id: 1 });
  } catch (error) {
    logger.error('Failed to update settings:', error);
    res.status(500).json({ message: error.message });
  }
};

const regenerateSmsApiKey = async (req, res) => {
  try {
    if (req.user.role !== 'owner') return res.status(403).json({ message: 'Owner only' });

    const newKey = Array.from({length: 48}, () => Math.floor(Math.random() * 16).toString(16)).join('');

    let settings = await Settings.findOne();
    if (!settings) settings = new Settings();

    settings.smsWebhookKey = newKey;
    await settings.save();
    
    await CacheService.invalidateSettings();

    LogService.info(
      `SMS Webhook API Key regenerated by admin`,
      'ADMIN_REGENERATE_SMS_KEY',
      null,
      { adminId: req.user.id }
    ).catch(err => logger.error('Audit logging failed:', err));

    res.json({ key: newKey });
  } catch (error) {
    logger.error('SMS Key Regeneration Failed:', error);
    res.status(500).json({ 
      message: error.message || 'Internal server error'
    });
  }
};

module.exports = { getSettings, updateSettings, regenerateSmsApiKey };
